version: "3.9"
services:
  db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules

  # www:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: www_docker_symfony
  #   ports:
  #     - "8741:80"
  #   volumes:
  #     - ./api/vhosts:/etc/apache2/sites-enabled
  #     - ./:/var/www
  #   depends_on:
  #     - db
  #   restart: always
  #   networks:
  #     - dev

networks:
  dev:

volumes:
  db-data:
