version: "3.9"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chstack
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
      
  front:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - dev
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
      - /app/node_modules

  # www:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   container_name: www_docker_symfony
  #   ports:
  #     - "8741:80"
  #   volumes:
  #     - ./api/vhosts:/etc/apache2/sites-enabled
  #     - ./:/var/www
  #   depends_on:
  #     - db
  #   restart: always
  #   networks:
  #     - dev

networks:
  dev:

volumes:
  mysql-data:
